spring:
  application:
    name: employeeSystem
  datasource:
    url: jdbc:h2:mem:mydb
    username: av
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  port: 8085
